# Change baseurl before deploy
baseurl      = "https://crudwellflag.org.uk"
languageCode = "en-gb"
title        = "Crudwell Flood Action"

defaultContentLanguage = "en"
hasCJKLanguage = false

[pagination]
    pagerSize = 5

[cookies]
    enabled      = false
    showSettings = true

    [cookies.categories]
        analytics  = true
        functional = true
